<a href="https://colab.research.google.com/github/Bibhuti-MLAI/Time-Series-Forcasting/blob/main/Revenue_Forcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_absolute_percentage_error

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)
data_path = r"/content/drive/MyDrive/Alma Better/Revenue Forcasting/bfsi_revenue_forecasting_project/data/BFSI_Revenue_Forecasting_Dataset.xlsx"
RANDOM_STATE = 42

In [3]:
customer = pd.read_excel(data_path, sheet_name="Customer_Master")

In [4]:
customer.head()

,customer_id,customer_name,segment,industry,onboarding_date,credit_limit,risk_grade,geography
0,CUST00056,Client Enterprises 56,Medium,Pharma,15/11/18,10926167.91,C,NaN
1,CUST00052,Client Enterprises 52,Micro,Logistics,07/24/2018,25541292.36,B,Telangana
2,CUST00002,Client Enterprises 2,MSME,Logistics,17-10-2021,29729379.37,A,Maharashtra
3,CUST00089,Client Enterprises 89,SME,IT Services,04/18/2022,14092573.62,A,Delhi NCR
4,CUST00048,Client Enterprises 48,SME,Textiles,03/09/18,29928698.10,A+,Karnataka

In [5]:
invoice = pd.read_excel(data_path, sheet_name="Invoice_Data")
payment = pd.read_excel(data_path, sheet_name="Payment_Data")
repayment =pd.read_excel(data_path, sheet_name="Repayment_Data")

In [6]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      113 non-null    object
 1   customer_name    113 non-null    object
 2   segment          113 non-null    object
 3   industry         113 non-null    object
 4   onboarding_date  113 non-null    object
 5   credit_limit     104 non-null    float64
 6   risk_grade       98 non-null     object
 7   geography        107 non-null    object
dtypes: float64(1), object(7)
memory usage: 7.2+ KB

In [7]:
customer.describe().T

,count,mean,std,min,25%,50%,75%,max
credit_limit,104.0,2.464384e+07,1.384461e+07,583718.27,12734032.6,2.558577e+07,35548554.17,49400676.43

In [12]:
customer['customer_id'].count()

np.int64(113)